// this test is generated by deepseek-v4.1-flash
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:touchfish_client/l10n/app_localizations.dart';
import 'package:touchfish_client/models/message_model.dart';
import 'package:touchfish_client/screens/chat_detail/widgets/message_list_view.dart';
import 'package:touchfish_client/widgets/file_attachment_view.dart';

ChatMessage _message(
  int index, {
  String? clientMid,
  int? mid,
  MessageStatus status = MessageStatus.sent,
}) => ChatMessage(
  id: 'm$index',
  clientMid: clientMid,
  mid: mid,
  senderUid: 1,
  senderName: 'Alice',
  isMe: false,
  text: 'message $index',
  timestamp: DateTime.fromMillisecondsSinceEpoch(index * 1000),
  status: status,
);

ChatMessage _attachmentMessage(int index, {int? mid}) => ChatMessage(
  id: 'a$index',
  mid: mid,
  senderUid: 1,
  senderName: 'Alice',
  isMe: false,
  type: MessageType.file,
  text: '[FILE]',
  timestamp: DateTime.fromMillisecondsSinceEpoch(index * 1000),
  media: MessageMedia(
    path: 'hash$index',
    fileName: 'file$index.bin',
    fileSize: 1024,
    mimeType: 'application/octet-stream',
    fileHash: 'hash$index',
  ),
);

List<ChatMessage> _messages(int count) => [
  for (var i = 0; i < count; i++) _message(i, mid: i),
];

void main() {
  group('newlyAppendedMessageKeys', () {
    test('reports the tail message that just arrived', () {
      final before = _messages(3);
      final after = [...before, _message(3, mid: 3)];

      expect(newlyAppendedMessageKeys(before, after), {'3'});
    });

    test('prepended history is not a new message', () {
      final before = _messages(3);
      final after = [..._messages(2), ...before];

      expect(newlyAppendedMessageKeys(before, after), isEmpty);
    });

    test('bulk sync arrivals do not animate', () {
      final before = _messages(3);
      final after = [
        ...before,
        for (var i = 3; i < 30; i++) _message(i, mid: i),
      ];

      expect(newlyAppendedMessageKeys(before, after), isEmpty);
    });

    test('the first population of a room does not animate', () {
      expect(newlyAppendedMessageKeys(const [], _messages(2)), isEmpty);
    });

    test('the tail message being swapped by CDS still counts as an append', () {
      final before = [
        ..._messages(2),
        _message(2, clientMid: 'c2', status: MessageStatus.pending),
      ];
      final after = [
        ...before.take(2),
        _message(2, clientMid: 'c2', mid: 22, status: MessageStatus.sent),
        _message(3, mid: 3),
      ];

      expect(newlyAppendedMessageKeys(before, after), {'3'});
    });

    test('in-place updates (recall / ack) do not animate', () {
      final before = _messages(3);
      final after = [
        ...before.take(2),
        before.last.copyWith(status: MessageStatus.failed),
      ];

      expect(newlyAppendedMessageKeys(before, after), isEmpty);
    });
  });

  testWidgets('appending a message keeps existing bubble elements alive', (
    tester,
  ) async {
    final harness = GlobalKey<_MessageListHarnessState>();
    await tester.pumpWidget(
      _wrap(_MessageListHarness(key: harness, messages: _messages(8))),
    );
    await tester.pumpAndSettle();

    final bubble = find.byKey(const ValueKey('bubble-5'));
    final before = tester.element(bubble);

    harness.currentState!.appendWithEntrance([_message(8, mid: 8)]);
    await tester.pump();

    expect(identical(tester.element(bubble), before), isTrue);
    await tester.pumpAndSettle();
  });

  testWidgets('appending a message does not re-init media attachments', (
    tester,
  ) async {
    SharedPreferences.setMockInitialValues({});
    final harness = GlobalKey<_MessageListHarnessState>();
    await tester.pumpWidget(
      _wrap(
        _MessageListHarness(
          key: harness,
          messages: [_message(0, mid: 0), _attachmentMessage(1, mid: 1)],
        ),
      ),
    );
    await tester.pumpAndSettle();

    final attachment = find.byType(FileAttachmentView);
    expect(attachment, findsOneWidget);
    final before = tester.element(attachment);

    harness.currentState!.appendWithEntrance([_message(2, mid: 2)]);
    await tester.pump(const Duration(milliseconds: 16));
    await tester.pump(const Duration(milliseconds: 16));

    expect(identical(tester.element(find.byType(FileAttachmentView)), before), isTrue);
    await tester.pumpAndSettle();
  });

  testWidgets('ack backfilling the server mid keeps the bubble element alive', (
    tester,
  ) async {
    final harness = GlobalKey<_MessageListHarnessState>();
    await tester.pumpWidget(
      _wrap(
        _MessageListHarness(
          key: harness,
          messages: [
            _message(0, mid: 0),
            _message(1, clientMid: 'c1', status: MessageStatus.pending),
          ],
        ),
      ),
    );
    await tester.pumpAndSettle();

    final bubble = find.byKey(const ValueKey('bubble-c1'));
    final before = tester.element(bubble);

    // pending -> sent：clientMid 不变，只是回填了 mid
    harness.currentState!.replaceLast([_message(1, clientMid: 'c1', mid: 1)]);
    await tester.pump();

    expect(identical(tester.element(bubble), before), isTrue);
  });

  testWidgets('every send animates even after CDS swaps the previous message', (
    tester,
  ) async {
    final harness = GlobalKey<_CdsBackedHarnessState>();
    await tester.pumpWidget(
      _wrap(
        _CdsBackedHarness(
          key: harness,
          messages: [for (var i = 0; i < 5; i++) _message(i, mid: i)],
        ),
      ),
    );
    await tester.pumpAndSettle();

    Finder entranceOf(String key) => find.descendant(
      of: find.byKey(ValueKey('bubble-$key')),
      matching: find.byType(FadeTransition),
    );

    for (var n = 5; n < 8; n++) {
      // 上一条消息被 CDS 静默换上只有 roomSeq 变化的新对象
      harness.currentState!.swapTailInvisibly(n * 10);
      await tester.pump();
      harness.currentState!.sendFromCds([_message(n, mid: n)]);
      await tester.pump(const Duration(milliseconds: 16));
      await tester.pump(const Duration(milliseconds: 16));

      expect(find.byKey(ValueKey('bubble-$n')), findsOneWidget);
      expect(entranceOf('$n'), findsOneWidget);
      await tester.pumpAndSettle();
    }
  });

  testWidgets('only the arriving message opts into the entrance animation', (
    tester,
  ) async {
    final harness = GlobalKey<_MessageListHarnessState>();
    await tester.pumpWidget(
      _wrap(_MessageListHarness(key: harness, messages: _messages(3))),
    );
    await tester.pumpAndSettle();

    harness.currentState!.appendWithEntrance([_message(3, mid: 3)]);
    // 插入的新 item 比 provider 通知晚一帧才被 sliver 构建出来
    await tester.pump(const Duration(milliseconds: 16));
    await tester.pump(const Duration(milliseconds: 16));

    Finder entranceOf(int index) => find.descendant(
      of: find.byKey(ValueKey('bubble-$index')),
      matching: find.byType(FadeTransition),
    );

    expect(entranceOf(3), findsOneWidget);
    expect(entranceOf(0), findsNothing);

    // 动画确实在跑：淡入 + 高度撑开
    final bubble = find.byKey(const ValueKey('bubble-3'));
    final earlyHeight = tester.getSize(bubble).height;
    await tester.pump(const Duration(milliseconds: 150));
    expect(
      tester.widget<FadeTransition>(entranceOf(3)).opacity.value,
      lessThan(1),
    );
    final midHeight = tester.getSize(bubble).height;
    expect(midHeight, greaterThan(earlyHeight));

    await tester.pumpAndSettle();
    expect(tester.widget<FadeTransition>(entranceOf(3)).opacity.value, 1);
    final fullHeight = tester.getSize(bubble).height;
    expect(fullHeight, greaterThan(midHeight));

    // 播过一次的气泡不会再播（换一条新消息重建整行时高度保持完整）
    harness.currentState!.appendWithEntrance([_message(4, mid: 4)]);
    await tester.pump(const Duration(milliseconds: 16));
    await tester.pump(const Duration(milliseconds: 16));
    expect(entranceOf(3), findsOneWidget);
    expect(tester.getSize(bubble).height, fullHeight);
    await tester.pumpAndSettle();
  });
}

Widget _wrap(Widget child) => MaterialApp(
  localizationsDelegates: AppLocalizations.localizationsDelegates,
  supportedLocales: AppLocalizations.supportedLocales,
  home: Scaffold(body: child),
);

/// 带 CDS/provider 两层的壳：
///
/// - CDS 侧（[_cds]）会被静默换成新对象（只有 roomSeq 变化）
/// - provider 侧（[_messages]）判定渲染内容没变就跳过更新，屏幕一直拿着旧对象
class _CdsBackedHarness extends StatefulWidget {
  final List<ChatMessage> messages;

  const _CdsBackedHarness({super.key, required this.messages});

  @override
  State<_CdsBackedHarness> createState() => _CdsBackedHarnessState();
}

class _CdsBackedHarnessState extends State<_CdsBackedHarness> {
  final ScrollController controller = ScrollController();
  late List<ChatMessage> _cds = [...widget.messages];
  late List<ChatMessage> _messages = List.of(_cds);
  final Set<String> _entranceKeys = {};

  void sendFromCds(List<ChatMessage> messages) {
    _cds = [..._cds, ...messages];
    _publish();
  }

  /// 复刻 _adoptServerFields：同一条逻辑消息换成新对象，只有 roomSeq 变了。
  void swapTailInvisibly(int roomSeq) {
    final swapped = [..._cds];
    swapped[swapped.length - 1] = swapped.last.copyWith(roomSeq: roomSeq);
    _cds = swapped;
    _publish();
  }

  void _publish() {
    final needsUpdate =
        _messages.length != _cds.length ||
        ![
          for (var i = 0; i < _cds.length; i++)
            ChatMessage.sameRenderedContent(_cds[i], _messages[i]),
        ].every((same) => same);
    if (!needsUpdate) return;
    setState(() {
      _entranceKeys.addAll(newlyAppendedMessageKeys(_messages, _cds));
      _messages = List.of(_cds);
    });
  }

  @override
  void dispose() {
    controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return SizedBox(
      height: 400,
      child: MessageListView(
        messages: _messages,
        entranceKeys: _entranceKeys,
        scrollController: controller,
        galleryItems: const [],
        imageIndexById: const {},
        essenceMids: const [],
        pinnedMessages: const [],
        essenceEnabled: false,
        currentRoom: null,
        canModerateGroup: false,
        onRefresh: () {},
        onReply: (_) {},
        onForward: (_) {},
        onRecall: (_) {},
        onQuoteTap: (_) {},
        onPinToggle: (_) {},
        onEssenceToggle: (_) {},
        canRecall: (_) => false,
        canDeleteLocally: (_) => false,
        noMessagesText: 'No messages',
        colorScheme: Theme.of(context).colorScheme,
      ),
    );
  }
}

class _MessageListHarness extends StatefulWidget {
  final List<ChatMessage> messages;

  const _MessageListHarness({super.key, required this.messages});

  @override
  State<_MessageListHarness> createState() => _MessageListHarnessState();
}

class _MessageListHarnessState extends State<_MessageListHarness> {
  final ScrollController controller = ScrollController();
  late List<ChatMessage> _messages = [...widget.messages];
  final Set<String> _entranceKeys = {};

  void appendWithEntrance(List<ChatMessage> messages) => setState(() {
    final next = [..._messages, ...messages];
    _entranceKeys.addAll(newlyAppendedMessageKeys(_messages, next));
    _messages = next;
  });

  void replaceLast(List<ChatMessage> messages) => setState(() {
    _messages = [..._messages]
      ..removeLast()
      ..addAll(messages);
  });

  @override
  void dispose() {
    controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return SizedBox(
      height: 400,
      child: MessageListView(
        messages: _messages,
        entranceKeys: _entranceKeys,
        scrollController: controller,
        galleryItems: const [],
        imageIndexById: const {},
        essenceMids: const [],
        pinnedMessages: const [],
        essenceEnabled: false,
        currentRoom: null,
        canModerateGroup: false,
        onRefresh: () {},
        onReply: (_) {},
        onForward: (_) {},
        onRecall: (_) {},
        onQuoteTap: (_) {},
        onPinToggle: (_) {},
        onEssenceToggle: (_) {},
        canRecall: (_) => false,
        canDeleteLocally: (_) => false,
        noMessagesText: 'No messages',
        colorScheme: Theme.of(context).colorScheme,
      ),
    );
  }
}
