import 'dart:async';
import 'dart:io';
import 'dart:math' as math;
import 'dart:typed_data';

import 'package:flutter/material.dart';
import 'package:flutter/foundation.dart' show kIsWeb;
import 'package:flutter_hooks/flutter_hooks.dart';
import 'package:media_kit/media_kit.dart';
import 'package:material_symbols_icons/symbols.dart';

import '../../services/file_cache_service.dart';
import '../../services/media_proxy_service.dart';
import '../../services/api/tf_api_client.dart';
import '../../utils/talker.dart';

/// 语音消息气泡
/// 64 柱波形、圆形播放/暂停按钮、mm:ss / mm:ss，波形可拖动
/// Generated by DeepSeek
class VoiceMessageBubble extends HookWidget {
  final String audioPath;
  final Uint8List? audioBytes;
  final int? durationMs;

  /// 服务端文件 hash（收到的语音消息 path 即 hash）；用于解析真实 URL。
  final String? fileHash;

  const VoiceMessageBubble({
    super.key,
    required this.audioPath,
    this.audioBytes,
    this.durationMs,
    this.fileHash,
  });

  /// 将 path/hash/本地路径统一解析成可播放/可下载的地址。
  static Future<String> resolveCanonical(String path, String? fileHash) async {
    final uri = Uri.tryParse(path);
    if (uri != null && (uri.scheme == 'http' || uri.scheme == 'https')) {
      return path;
    }
    if (!kIsWeb && path.isNotEmpty && (path.startsWith('/') || path.contains(':'))) {
      if (File(path).existsSync()) return path;
    }
    return TfApiClient.instance.getFileUrl(fileHash ?? path);
  }

  @override
  Widget build(BuildContext context) {
    final player = useMemoized(() {
      MediaKit.ensureInitialized();
      return Player();
    }, []);

    final duration = useState(Duration(milliseconds: durationMs ?? 0));
    final position = useState(Duration.zero);
    final isPlaying = useState(false);
    final isScrubbing = useState(false);
    final scrubPosition = useState(Duration.zero);
    final waveformBars = useState<List<double>?>(null);
    final waveformSource = useState<String?>(null);

    final total = duration.value > Duration.zero
        ? duration.value
        : Duration(milliseconds: durationMs ?? 0);
    final shownPosition = isScrubbing.value ? scrubPosition.value : position.value;
    final totalMs = total.inMilliseconds <= 0
        ? 1.0
        : total.inMilliseconds.toDouble();

    useEffect(() {
      var disposed = false;
      final subs = <StreamSubscription<dynamic>>[
        player.stream.position.listen((value) {
          position.value = value;
          if (!isScrubbing.value) scrubPosition.value = value;
        }),
        player.stream.duration.listen((value) {
          if (value > Duration.zero) duration.value = value;
        }),
        player.stream.playing.listen((value) => isPlaying.value = value),
      ];

      unawaited(() async {
        try {
          final canonical = await resolveCanonical(audioPath, fileHash);
          final source = kIsWeb
              ? canonical
              : await MediaProxyService.instance.resolveUrl(canonical);
          if (!disposed) {
            await player.open(Media(source));
          }
        } catch (e) {
          talker.error('VoiceMessageBubble open failed', e);
        }
      }());

      return () {
        disposed = true;
        for (final sub in subs) {
          sub.cancel();
        }
        player.dispose();
      };
    }, []);

    Future<void> generateWaveform() async {
      if (waveformSource.value == audioPath) return;
      waveformSource.value = audioPath;
      try {
        Uint8List bytes;
        if (audioBytes != null) {
          bytes = audioBytes!;
        } else {
          final canonical = await resolveCanonical(audioPath, fileHash);
          final uri = Uri.tryParse(canonical);
          if (!kIsWeb && uri != null && uri.scheme == 'file') {
            bytes = await File.fromUri(uri).readAsBytes();
          } else if (!kIsWeb && canonical.isNotEmpty && !canonical.startsWith('http')) {
            bytes = await File(canonical).readAsBytes();
          } else {
            final file = await FileCacheService.instance.getFile(canonical);
            if (file == null) return;
            bytes = await file.readAsBytes();
          }
        }
        if (bytes.isEmpty) return;
        waveformBars.value = _computeWaveform(bytes);
      } catch (e) {
        talker.warning('VoiceMessageBubble waveform failed: $e');
      }
    }

    useEffect(() {
      unawaited(generateWaveform());
      return null;
    }, [audioPath, fileHash]);

    return Container(
      constraints: const BoxConstraints(maxWidth: 320),
      padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 8),
      decoration: BoxDecoration(
        color: Theme.of(context).colorScheme.surfaceContainerLow,
        borderRadius: BorderRadius.circular(12),
      ),
      child: Row(
        mainAxisSize: MainAxisSize.max,
        children: [
          IconButton(
            visualDensity: VisualDensity.compact,
            icon: Icon(
              isPlaying.value ? Symbols.pause_circle : Symbols.play_circle,
              size: 22,
            ),
            onPressed: () async {
              if (isPlaying.value) {
                await player.pause();
              } else {
                final atEnd = totalMs > 0 &&
                    position.value.inMilliseconds >= total.inMilliseconds - 250;
                if (atEnd) await player.seek(Duration.zero);
                await player.play();
              }
            },
          ),
          Expanded(
            child: Row(
              children: [
                SizedBox(
                  height: 28,
                  width: 180,
                  child: _VoiceWaveformProgress(
                    bars: waveformBars.value,
                    progress: (shownPosition.inMilliseconds / totalMs).clamp(
                      0.0,
                      1.0,
                    ),
                    onSeekUpdate: (ratio) {
                      isScrubbing.value = true;
                      scrubPosition.value = Duration(
                        milliseconds: (ratio.clamp(0.0, 1.0) * totalMs).toInt(),
                      );
                    },
                    onSeekEnd: () async {
                      await player.seek(scrubPosition.value);
                      isScrubbing.value = false;
                    },
                  ),
                ),
                const SizedBox(width: 8),
                Flexible(
                  flex: 1,
                  child: Text(
                    '${_formatSeconds(shownPosition)} / ${_formatSeconds(total)}',
                    maxLines: 1,
                    overflow: TextOverflow.ellipsis,
                    textAlign: TextAlign.right,
                    style: TextStyle(
                      fontSize: 11,
                      color: Theme.of(context).colorScheme.onSurfaceVariant,
                    ),
                  ),
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }

  static String _formatSeconds(Duration duration) {
    final totalSeconds = (duration.inMilliseconds / 1000).floor().clamp(
      0,
      99999,
    );
    final minutes = totalSeconds ~/ 60;
    final seconds = totalSeconds % 60;
    return '${minutes.toString().padLeft(2, '0')}:'
        '${seconds.toString().padLeft(2, '0')}';
  }

  /// 由音频字节计算 64 柱归一化波形（移植自 Solian，跳过文件头）。
  static List<double> _computeWaveform(Uint8List bytes) {
    const barCount = 64;
    final bars = <double>[];
    final window = (bytes.length / barCount).ceil();
    const startOffset = 1024;

    for (var i = 0; i < barCount; i++) {
      final start = math.min(startOffset + (i * window), bytes.length);
      final end = math.min(start + window, bytes.length);
      if (start >= end) {
        bars.add(0.12);
        continue;
      }
      var sum = 0.0;
      var samples = 0;
      for (var j = start; j < end; j += 8) {
        sum += (bytes[j] - 128).abs().toDouble();
        samples++;
      }
      final normalized = samples == 0
          ? 0.12
          : math.sqrt((sum / samples) / 128.0);
      bars.add(normalized.clamp(0.12, 1.0));
    }
    return bars;
  }
}

class _VoiceWaveformProgress extends StatelessWidget {
  final List<double>? bars;
  final double progress;
  final ValueChanged<double>? onSeekUpdate;
  final Future<void> Function()? onSeekEnd;

  const _VoiceWaveformProgress({
    required this.bars,
    required this.progress,
    this.onSeekUpdate,
    this.onSeekEnd,
  });

  @override
  Widget build(BuildContext context) {
    final colorScheme = Theme.of(context).colorScheme;
    final waveform = bars;

    if (waveform == null || waveform.isEmpty) {
      return ClipRRect(
        borderRadius: BorderRadius.circular(999),
        child: LinearProgressIndicator(
          value: progress.clamp(0.0, 1.0),
          minHeight: 4,
          color: colorScheme.primary,
          backgroundColor: colorScheme.surfaceContainerHighest,
        ),
      );
    }

    return LayoutBuilder(
      builder: (context, constraints) {
        final barCount = waveform.length;
        const spacing = 1.0;
        final barWidth =
            ((constraints.maxWidth - (barCount - 1) * spacing) / barCount)
                .clamp(1.5, 3.2);
        final playedBars = progress.clamp(0.0, 1.0) * barCount;

        double ratioFromDx(double dx) {
          if (constraints.maxWidth <= 0) return 0;
          return (dx / constraints.maxWidth).clamp(0.0, 1.0);
        }

        return GestureDetector(
          behavior: HitTestBehavior.opaque,
          onTapDown: onSeekUpdate == null
              ? null
              : (details) {
                  onSeekUpdate!(ratioFromDx(details.localPosition.dx));
                  if (onSeekEnd != null) unawaited(onSeekEnd!());
                },
          onHorizontalDragStart: onSeekUpdate == null
              ? null
              : (details) =>
                    onSeekUpdate!(ratioFromDx(details.localPosition.dx)),
          onHorizontalDragUpdate: onSeekUpdate == null
              ? null
              : (details) =>
                    onSeekUpdate!(ratioFromDx(details.localPosition.dx)),
          onHorizontalDragEnd: onSeekEnd == null
              ? null
              : (_) => unawaited(onSeekEnd!()),
          child: Align(
            alignment: Alignment.centerLeft,
            child: Row(
              mainAxisSize: MainAxisSize.min,
              crossAxisAlignment: CrossAxisAlignment.center,
              children: List.generate(barCount, (index) {
                final normalized = waveform[index].clamp(0.12, 1.0);
                final height = 5 + (normalized * 15);
                final fill = (playedBars - index).clamp(0.0, 1.0);
                return AnimatedContainer(
                  duration: const Duration(milliseconds: 120),
                  curve: Curves.easeOutCubic,
                  width: barWidth,
                  height: height,
                  margin: EdgeInsets.only(
                    right: index == barCount - 1 ? 0 : spacing,
                  ),
                  decoration: BoxDecoration(
                    color: Color.lerp(
                      colorScheme.surfaceContainerHighest,
                      colorScheme.primary,
                      fill,
                    ),
                    borderRadius: BorderRadius.circular(2),
                  ),
                );
              }),
            ),
          ),
        );
      },
    );
  }
}
